<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327144031 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE joueur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pseudo VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FD71A9C586CC499D ON joueur (pseudo)');
        $this->addSql('CREATE TABLE mini_jeu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, nom_mini_jeu VARCHAR(100) NOT NULL, description_mini_jeu VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE partie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nb_reponse INT NOT NULL, date_heure_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_heure_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, score_total INT NOT NULL, joueur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_59B1F3DA9E2D76C ON partie (joueur_id)');
        $this->addSql('CREATE TABLE utilise (partie_id INT NOT NULL, mini_jeu_id INT NOT NULL, PRIMARY KEY (partie_id, mini_jeu_id))');
        $this->addSql('CREATE INDEX IDX_28917DEFE075F7A4 ON utilise (partie_id)');
        $this->addSql('CREATE INDEX IDX_28917DEF6EF1A51C ON utilise (mini_jeu_id)');
        $this->addSql('CREATE TABLE question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, enonce VARCHAR(255) NOT NULL, element_adeviner VARCHAR(100) NOT NULL, difficulte INT NOT NULL, choix_possibles JSON NOT NULL, mini_jeu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6F7494E6EF1A51C ON question (mini_jeu_id)');
        $this->addSql('CREATE TABLE reponse (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reponse_donnee VARCHAR(100) DEFAULT NULL, est_correcte BOOLEAN NOT NULL, score_obtenu INT NOT NULL, temps_reponse_sec INT DEFAULT NULL, question_id INT NOT NULL, partie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5FB6DEC71E27F6BF ON reponse (question_id)');
        $this->addSql('CREATE INDEX IDX_5FB6DEC7E075F7A4 ON reponse (partie_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE partie ADD CONSTRAINT FK_59B1F3DA9E2D76C FOREIGN KEY (joueur_id) REFERENCES joueur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilise ADD CONSTRAINT FK_28917DEFE075F7A4 FOREIGN KEY (partie_id) REFERENCES partie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilise ADD CONSTRAINT FK_28917DEF6EF1A51C FOREIGN KEY (mini_jeu_id) REFERENCES mini_jeu (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494E6EF1A51C FOREIGN KEY (mini_jeu_id) REFERENCES mini_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT FK_5FB6DEC71E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT FK_5FB6DEC7E075F7A4 FOREIGN KEY (partie_id) REFERENCES partie (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE partie DROP CONSTRAINT FK_59B1F3DA9E2D76C');
        $this->addSql('ALTER TABLE utilise DROP CONSTRAINT FK_28917DEFE075F7A4');
        $this->addSql('ALTER TABLE utilise DROP CONSTRAINT FK_28917DEF6EF1A51C');
        $this->addSql('ALTER TABLE question DROP CONSTRAINT FK_B6F7494E6EF1A51C');
        $this->addSql('ALTER TABLE reponse DROP CONSTRAINT FK_5FB6DEC71E27F6BF');
        $this->addSql('ALTER TABLE reponse DROP CONSTRAINT FK_5FB6DEC7E075F7A4');
        $this->addSql('DROP TABLE joueur');
        $this->addSql('DROP TABLE mini_jeu');
        $this->addSql('DROP TABLE partie');
        $this->addSql('DROP TABLE utilise');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE reponse');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
